tls:
  certificates:
    - certFile: /certs/traefik-external/cert.pem
      keyFile: /certs/traefik-external/key.pem

http:
  middlewares:
    keycloak-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Port: "8443"

  serversTransports:
    keycloak-transport:
      certificates:
        - certFile: /certs/traefik-internal/cert.pem
          keyFile: /certs/traefik-internal/key.pem
      rootCAs:
        - /certs/keycloak1-cert.pem
        - /certs/keycloak2-cert.pem

  routers:
    keycloak:
      entryPoints:
        - websecure
      rule: "HostRegexp(`^.+$`)"
      tls: {}
      service: keycloak
      middlewares:
        - keycloak-headers

  services:
    keycloak:
      loadBalancer:
        serversTransport: keycloak-transport
        healthCheck:
          path: /health/ready
          port: 9000
          scheme: https
          interval: "5s"
          timeout: "3s"
        servers:
          - url: "https://keycloak1:8443"
          - url: "https://keycloak2:8443"