# =========================================================================
# NOTE: ADMIN UI hostname and port ISOLATION
#   - Uncomment 'KC_HOSTNAME_ADMIN' in keycloak1 and keycloak2 (line 39 and 94)
#   - Uncomment port '8444:8444' under the traefik service (line 191)
# =========================================================================
services:
  postgres:
    image: mirror.gcr.io/postgres:18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak1:
    image: quay.io/keycloak/keycloak:26.6.3
    command: start
    environment:
      # DB
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      # Metrics / Health
      KC_METRICS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_EVENT_METRICS_USER_TAGS: "realm,idp,clientId"
      KC_HEALTH_ENABLED: "true"
      # Hostname / HTTPS
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: "https://${KC_HOST}:8443"
    # Uncomment if you want to have the admin UI and admin API on a separate hostname and port.
    # KC_HOSTNAME_ADMIN: "https://${KC_HOST}:8444"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem
      KC_HTTPS_CLIENT_AUTH: required
      KC_HTTPS_TRUST_STORE_FILE: /opt/keycloak/conf/https-truststore/traefik-internal-cert.pem
      KC_HTTPS_MANAGEMENT_CLIENT_AUTH: none
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Enable the access log to see as requests arrive on at Keycloak
      KC_HTTP_ACCESS_LOG_ENABLED: "true"
      # Not recommended in production
      # HTTP headers can contain sensitive information (falls under the purview of the GDPR or similar)
      KC_HTTP_ACCESS_LOG_PATTERN: "long"
      # Client certificate lookup via the dedicated Traefik provider
      KC_SPI_X509CERT_LOOKUP__PROVIDER: traefik
      # Misc
      KC_SHUTDOWN_DELAY: 8s
      KC_SPI_CACHE_EMBEDDED__DEFAULT__NODE_NAME: keycloak1
    volumes:
      - source: ./certs/keycloak1
        target: /opt/keycloak/certs
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-internal/cert.pem
        target: /opt/keycloak/conf/https-truststore/traefik-internal-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  keycloak2:
    image: quay.io/keycloak/keycloak:26.6.3
    command: start
    environment:
      # DB
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      # Metrics / Health
      KC_METRICS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_EVENT_METRICS_USER_TAGS: "realm,idp,clientId"
      KC_HEALTH_ENABLED: "true"
      # Hostname / HTTPS
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: "https://${KC_HOST}:8443"
      # Uncomment if you want to have the admin UI and admin API on a separate hostname and port.
      # KC_HOSTNAME_ADMIN: "https://${KC_HOST}:8444"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem
      KC_HTTPS_CLIENT_AUTH: required
      KC_HTTPS_TRUST_STORE_FILE: /opt/keycloak/conf/https-truststore/traefik-internal-cert.pem
      KC_HTTPS_MANAGEMENT_CLIENT_AUTH: none
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Enable the access log to see as requests arrive on at Keycloak
      KC_HTTP_ACCESS_LOG_ENABLED: "true"
      # Not recommended in production
      # HTTP headers can contain sensitive information (falls under the purview of the GDPR or similar)
      KC_HTTP_ACCESS_LOG_PATTERN: "long"
      # Client certificate lookup via the dedicated Traefik provider
      KC_SPI_X509CERT_LOOKUP__PROVIDER: traefik
      # Misc
      KC_SHUTDOWN_DELAY: 8s
      KC_SPI_CACHE_EMBEDDED__DEFAULT__NODE_NAME: keycloak2
    volumes:
      - source: ./certs/keycloak2
        target: /opt/keycloak/certs
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-internal/cert.pem
        target: /opt/keycloak/conf/https-truststore/traefik-internal-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  traefik:
    image: mirror.gcr.io/traefik:v3.6
    volumes:
      - source: ./traefik.yaml
        target: /etc/traefik/traefik.yaml
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./keycloak.yaml
        target: /mnt/keycloak.yaml
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-external/cert.pem
        target: /certs/traefik-external/cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-external/key.pem
        target: /certs/traefik-external/key.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-internal/cert.pem
        target: /certs/traefik-internal/cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/traefik-internal/key.pem
        target: /certs/traefik-internal/key.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/keycloak1/cert.pem
        target: /certs/keycloak1-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/keycloak2/cert.pem
        target: /certs/keycloak2-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/client-ca/chain.pem
        target: /certs/client-ca-chain.pem
        type: bind
        read_only: true
        bind:
          selinux: z
    ports:
      - "8443:8443"
     #  Uncomment if you want to have the admin UI and admin API on a separate hostname and port.
     # - "8444:8444"
      - "8080:8080"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
    internal: true
