entryPoints:
  keycloak:
    address: ":8443"
api:
  dashboard: true
  insecure: true
log:
  level: INFO
accessLog:
  format: json
  fields:
    # Not recommended in production
    # HTTP headers can contain sensitive information (falls under the purview of the GDPR or similar)
    headers:
      defaultMode: keep
providers:
  file:
    directory: "/mnt"
