# =========================================================================
# NOTE: ADMIN UI hostname and port ISOLATION
#   - Uncomment keycloak-admin entry point (keycloak-admin)
# =========================================================================
entryPoints:
  keycloak:
    address: ":8443"
# ADMIN UI hostname and port ISOLATION
# Uncomment if you want to have the admin UI and admin API on a separate hostname and port.
#  keycloak-admin:
#    address: ":8444"
api:
  dashboard: true
  insecure: true
log:
  level: INFO
accessLog:
  format: json
  fields:
    # Not recommended in production
    # HTTP headers can contain sensitive information (falls under the purview of the GDPR or similar)
    headers:
      defaultMode: keep
providers:
  file:
    directory: "/mnt"