language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak/quickstarts

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"
  matrix:
    - TESTS=group1
    - TESTS=group2
    - TESTS=group3

before_install:
  - ./travis-server.sh

install:
  - travis_wait 20 mvn -s maven-settings.xml clean install --no-snapshot-updates -DskipTests=true -Denforcer.skip=true -B -V -q
  - mvn -s maven-settings.xml -Padd-datasource install -DskipTests=true -Denforcer.skip=true -f user-storage-jpa -q

before_script:
  - export MAVEN_SKIP_RC=true

script:
  - ./travis-run-tests.sh $TESTS

after_install:
  - ./scripts/stop-server.sh
  - kill -9 `cat pid.txt`

sudo: false
