services:
  postgres:
    image: mirror.gcr.io/postgres:18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak    
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak1:
    image: quay.io/keycloak/keycloak:26.6
    command: start
    environment:
      # DB
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      # Metrics / Health
      KC_METRICS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_EVENT_METRICS_USER_TAGS: "realm,idp,clientId"
      KC_HEALTH_ENABLED: "true"
      # Hostname / HTTPS
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME: "${KC_HOST}"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem      
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Enable the access log to see as requests arrive on at Keycloak
      KC_HTTP_ACCESS_LOG_ENABLED: "true"
      # Misc
      KC_SHUTDOWN_DELAY: 30s
      KC_SHUTDOWN_TIMEOUT: 30s
      KC_SPI_CACHE_EMBEDDED__DEFAULT__NODE_NAME: keycloak1      
    volumes:
      - source: ./certs/keycloak1
        target: /opt/keycloak/certs
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/haproxy-internal/cert.pem
        target: /opt/keycloak/conf/truststores/haproxy-internal-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  keycloak2:
    image: quay.io/keycloak/keycloak:26.6
    command: start
    environment:
      # DB
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      # Metrics / Health
      KC_METRICS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_EVENT_METRICS_USER_TAGS: "realm,idp,clientId"
      KC_HEALTH_ENABLED: "true"
      # Hostname / HTTPS
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME: "${KC_HOST}"
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key.pem
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      # Enable the access log to see as requests arrive on at Keycloak
      KC_HTTP_ACCESS_LOG_ENABLED: "true"
      # Misc
      KC_SHUTDOWN_DELAY: 30s
      KC_SHUTDOWN_TIMEOUT: 30s
      KC_SPI_CACHE_EMBEDDED__DEFAULT__NODE_NAME: keycloak2
    volumes:
      - source: ./certs/keycloak2
        target: /opt/keycloak/certs
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/haproxy-internal/cert.pem
        target: /opt/keycloak/conf/truststores/haproxy-internal-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  haproxy:
    image: mirror.gcr.io/haproxy:3.3
    volumes:
      - source: ./haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/haproxy/combined.pem
        target: /mnt/certs/haproxy.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/haproxy-internal/combined.pem
        target: /mnt/certs/haproxy-internal.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/keycloak1/cert.pem
        target: /mnt/certs/keycloak1-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
      - source: ./certs/keycloak2/cert.pem
        target: /mnt/certs/keycloak2-cert.pem
        type: bind
        read_only: true
        bind:
          selinux: z
    ports:
      - "8443:8443"
      - "8404:8404"
    depends_on:
      - keycloak1
      - keycloak2
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
    internal: true
