tcp:
  routers:
    keycloak-router:
      rule: "HostSNI(`*`)"
      service: "keycloak-service"
      priority: 100
      entryPoints:
        - "websecure"
      tls:
        passthrough: true  # Forward encrypted traffic as-is

  serversTransports:
    kc-passthrough:
      proxyProtocol:
        version: 2

  services:
    keycloak-service:
      loadBalancer:
        serversTransport: kc-passthrough
        healthCheck:
          interval: "5s"
          timeout: "3s"
        servers:
          - address: "keycloak1:8443"
          - address: "keycloak2:8443"